# Generated by Django 3.0.3 on 2020-12-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201206_1216'),
        ('login', '0004_auto_20200314_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomManager',
            new_name='VenueManager',
        ),
    ]
