# Generated by Django 3.0.3 on 2020-12-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200314_1916'),
        ('booking', '0007_remove_rooms_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Venues',
        ),
    ]
