# Generated by Django 3.0.3 on 2020-12-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201206_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_no',
            new_name='venue_id',
        ),
        migrations.RenameField(
            model_name='venues',
            old_name='room_no',
            new_name='venue_id',
        ),
        migrations.RenameField(
            model_name='venues',
            old_name='room_image',
            new_name='venue_image',
        ),
        migrations.RenameField(
            model_name='venues',
            old_name='room_type',
            new_name='venue_type',
        ),
    ]
