# Generated by Django 3.0.3 on 2020-12-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20201206_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='location',
            field=models.CharField(default='Gwalior', max_length=100),
        ),
    ]
