# Generated by Django 3.0.3 on 2020-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_venues_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
